##Select columns
columns_select = ['unique_subject_id', 'unique_hospital_admission_id', 'unique_icustay_id', 'source_db',
                    'admission_age', 'sex_female', 'weight_admission', 'height_admission', 'BMI_admission',
                    'los_hospital', 'los_ICU',
                    'comorbidity_score_value',
                    'in_hospital_mortality',
                    'race_ethnicity',
                    'pH',	'pCO2',	'pO2',
                    'SaO2', 'SaO2_timestamp',
                    'SpO2', 'SpO2_timestamp',
                    'vitals_tempc',
                    'vitals_heart_rate',
                    'vitals_resp_rate',
                    'vitals_mbp_ni',
                    'vitals_mbp_i',
                    'cbc_hemoglobin',
                    'cbc_hematocrit',
                    'cbc_mch',
                    'cbc_mchc',
                    'cbc_mcv',
                    'cbc_platelet',
                    'cbc_rbc',
                    'cbc_rdw',
                    'cbc_wbc',
                    'coag_fibrinogen',
                    'coag_inr',
                    'coag_pt',
                    'coag_ptt',
                    'bmp_sodium',
                    'bmp_potassium',
                    'bmp_chloride',
                    'bmp_bicarbonate',
                    'bmp_bun',
                    'bmp_creatinine',
                    'bmp_glucose',
                    'bmp_aniongap',
                    'bmp_calcium',
                    'bmp_lactate',
                    'hfp_alt',
                    'hfp_alp',
                    'hfp_ast',
                    'hfp_bilirubin_total',
                    'hfp_albumin',
                    'sofa_past_overall_24hr',
                    'sofa_past_coagulation_24hr',
                    'sofa_past_liver_24hr',
                    'sofa_past_cardiovascular_24hr',
                    'sofa_past_cns_24hr',
                    'sofa_past_renal_24hr',
                    'sofa_past_respiratory_24hr',
                    'sofa_future_overall_24hr' ,
                    'sofa_future_respiratory_24hr',
                    'sofa_overall_increased'
]

data = data[columns_select]